<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-09-22T20:34:44Z" name="Default suite" finished-at="2020-09-22T20:35:22Z" duration-ms="38547">
    <groups>
    </groups>
    <test started-at="2020-09-22T20:34:44Z" name="Default test" finished-at="2020-09-22T20:35:22Z" duration-ms="38547">
      <class name="tests.Factorial_Test">
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:tests.Factorial_Test@6ff29830]" started-at="2020-09-22T20:34:44Z" name="beforeMethod" finished-at="2020-09-22T20:34:51Z" duration-ms="6831" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="verifyButton()[pri:0, instance:tests.Factorial_Test@6ff29830]" started-at="2020-09-22T20:34:51Z" name="verifyButton" finished-at="2020-09-22T20:34:54Z" duration-ms="3131" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Calculate!] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Calculate!] but found []
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at tests.Factorial_Test.verifyButton(Factorial_Test.java:59)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyButton -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:tests.Factorial_Test@6ff29830]" started-at="2020-09-22T20:34:54Z" name="afterMethod" finished-at="2020-09-22T20:34:55Z" duration-ms="944" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:tests.Factorial_Test@6ff29830]" started-at="2020-09-22T20:34:55Z" name="beforeMethod" finished-at="2020-09-22T20:35:00Z" duration-ms="5273" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="verifyError()[pri:0, instance:tests.Factorial_Test@6ff29830]" started-at="2020-09-22T20:35:00Z" name="verifyError" finished-at="2020-09-22T20:35:00Z" duration-ms="281" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyError -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:tests.Factorial_Test@6ff29830]" started-at="2020-09-22T20:35:00Z" name="afterMethod" finished-at="2020-09-22T20:35:01Z" duration-ms="1089" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:tests.Factorial_Test@6ff29830]" started-at="2020-09-22T20:35:01Z" name="beforeMethod" finished-at="2020-09-22T20:35:07Z" duration-ms="6155" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="verifyOutput()[pri:0, instance:tests.Factorial_Test@6ff29830]" started-at="2020-09-22T20:35:07Z" name="verifyOutput" finished-at="2020-09-22T20:35:08Z" duration-ms="322" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyOutput -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:tests.Factorial_Test@6ff29830]" started-at="2020-09-22T20:35:08Z" name="afterMethod" finished-at="2020-09-22T20:35:09Z" duration-ms="966" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:tests.Factorial_Test@6ff29830]" started-at="2020-09-22T20:35:09Z" name="beforeMethod" finished-at="2020-09-22T20:35:15Z" duration-ms="6285" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="verifyText()[pri:0, instance:tests.Factorial_Test@6ff29830]" started-at="2020-09-22T20:35:15Z" name="verifyText" finished-at="2020-09-22T20:35:15Z" duration-ms="92" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyText -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:tests.Factorial_Test@6ff29830]" started-at="2020-09-22T20:35:15Z" name="afterMethod" finished-at="2020-09-22T20:35:16Z" duration-ms="893" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:tests.Factorial_Test@6ff29830]" started-at="2020-09-22T20:35:16Z" name="beforeMethod" finished-at="2020-09-22T20:35:21Z" duration-ms="5160" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="verifyTitle()[pri:0, instance:tests.Factorial_Test@6ff29830]" started-at="2020-09-22T20:35:21Z" name="verifyTitle" finished-at="2020-09-22T20:35:21Z" duration-ms="20" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTitle -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:tests.Factorial_Test@6ff29830]" started-at="2020-09-22T20:35:21Z" name="afterMethod" finished-at="2020-09-22T20:35:22Z" duration-ms="1052" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- tests.Factorial_Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
